name: 'SyncS3'

description: 'Uploads any changed files to S3.'

author: 'Richard Moore <me@ricmoo.com>'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_s3_bucket:
    description: 'AWS S3 Bucket'
    required: true
  source_folder:
    description: 'Source folder to sync'
    required: true
  source_prefix:
    description: 'Prefix to remove from source paths'
    required: false
  destination_prefix:
    description: 'Prefix to add to S3 keys (recommended to end in a '/')'
    required: false
  aws_cloudfront_id:
    description: 'AWS Cloudfront Distribution ID to flush'
    required: false
outputs:
  object_keys:
    description: 'S3 Key'
runs:
  using: 'node16'
  main: './dist/index.js'
